[build]
  publish = "."

[[redirects]]
  from = "/socket.io/*"
  to = "https://sonic-pro-qfa9.onrender.com/socket.io/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/health"
  to = "https://sonic-pro-qfa9.onrender.com/health"
  status = 200
  force = true

[[edge_functions]]
  function = "viewmind-welcome"
  path = "/*"

[[edge_functions]]
  function = "viewmind-music-room-v2"
  path = "/*"

[[edge_functions]]
  function = "viewmind-auth-v2"
  path = "/*"
