'use strict';
const http=require('http');
const express=require('express');
const {Server}=require('socket.io');
const app=express();
const server=http.createServer(app);
const io=new Server(server,{cors:{origin:process.env.CORS_ORIGIN||'*',methods:['GET','POST']},transports:['websocket','polling'],pingInterval:10000,pingTimeout:5000,maxHttpBufferSize:2e6});
const PORT=process.env.PORT||3000;
const rooms=new Map();
const online=new Map();
const users=new Map();
const CODE=/^[A-Z0-9]{6}$/;
const SYMBOLS=['🔴','🔵','🟢','🟡','🟣','🟠','🩷','🩵','⭐','💎','🔥','⚡','🍀','🌙','☀️','🎵','🎯','🎮'];
const CFG={easy:{cols:4,rows:4,on:6},medium:{cols:5,rows:5,on:9},hard:{cols:6,rows:6,on:13}};
app.use(express.json({limit:'256kb'}));
app.get('/health',(_q,r)=>r.json({ok:true,service:'SonicSync Socket.IO V9',now:Date.now()}));
app.get('/',(_q,r)=>r.json({ok:true,service:'SonicSync Socket.IO V9'}));
function cleanUser(u={}){const uid=String(u.uid||'').trim().slice(0,128),email=String(u.email||'').trim().toLowerCase().slice(0,320);return{uid,name:String(u.name||'Guest').slice(0,80),email,photo:u.photo?String(u.photo).slice(0,1000):null}}
function room(id,type='music',host=null){if(!rooms.has(id))rooms.set(id,{id,type,host,users:new Map(),sockets:new Map(),playback:null,game:null,memory:null,mind:null});return rooms.get(id)}
function members(r){return Object.fromEntries(r.users)}
function member(s,r){return !!r&&r.sockets.has(s.id)}
function emitState(s,r){s.emit('room:state',{roomId:r.id,type:r.type,hostUid:r.host,users:members(r),playback:r.playback,gameState:r.game});}
function emitUsers(r){io.to(r.id).emit('room:users',members(r));io.to(r.id).emit('room:state',{roomId:r.id,type:r.type,hostUid:r.host,users:members(r),playback:r.playback,gameState:r.game});}
function onlineAdd(s,u){if(!u.uid)return;users.set(u.uid,u);let set=online.get(u.uid);if(!set){set=new Set();online.set(u.uid,set)}set.add(s.id);s.data.uid=u.uid;s.data.user=u;s.emit('presence:registered',{uid:u.uid});}
function sendUid(uid,event,data){for(const sid of online.get(String(uid))||[])io.to(sid).emit(event,data)}
function leave(s,id,uid){id=String(id||'').toUpperCase();const r=rooms.get(id);if(!r)return;const actual=r.sockets.get(s.id);if(uid&&actual&&actual!==uid)return;r.sockets.delete(s.id);if(actual)r.users.delete(actual);s.leave(id);if(r.host===actual)r.host=r.users.keys().next().value||null;emitUsers(r);if(!r.sockets.size){clearTimeout(r.memory?.timer);clearTimeout(r.mind?.timer);rooms.delete(id)}}
function pattern(d,seed){const c=CFG[d]||CFG.easy,n=c.cols*c.rows,set=new Set();let x=(seed>>>0)||1;while(set.size<c.on){x^=x<<13;x^=x>>>17;x^=x<<5;set.add(Math.abs(x)%n)}return[...set]}
function startMemory(r){const d=r.memory.difficulty,c=d==='hard'?{x:6,y:6,t:4}:d==='medium'?{x:5,y:5,t:3}:{x:4,y:4,t:3},n=c.x*c.y,target=SYMBOLS[Math.floor(Math.random()*12)],cards=Array(n).fill(''),used=new Set();while(used.size<c.t)used.add(Math.floor(Math.random()*n));for(const i of used)cards[i]=target;for(let i=0;i<n;i++)if(!cards[i]){let z=SYMBOLS[Math.floor(Math.random()*SYMBOLS.length)];if(z===target)z=SYMBOLS[(SYMBOLS.indexOf(z)+1)%SYMBOLS.length];cards[i]=z}const now=Date.now();r.memory.round=(r.memory.round||0)+1;r.memory.cards=cards;r.memory.target=target;r.memory.roundId='mr-'+now+'-'+r.memory.round;r.memory.deadline=now+2200+15000;r.memory.picked={};for(const u of r.users.keys())r.memory.picked[u]=new Set();r.game={kind:'memory',round:r.memory.round,roundId:r.memory.roundId,startedAt:now,deadlineAt:r.memory.deadline};io.to(r.id).emit('memory:state',{roomId:r.id,round:r.memory.round,difficulty:d,cards,targetId:target,roundId:r.memory.roundId,previewMs:2200,deadlineAt:r.memory.deadline});clearTimeout(r.memory.timer);r.memory.timer=setTimeout(()=>{if(!rooms.has(r.id))return;io.to(r.id).emit('memory:round-result',{roomId:r.id,winnerUid:null,roundWins:r.memory.wins||{},scores:r.memory.scores||{}});startMemory(r)},17300)}
function startMind(r){const now=Date.now();r.mind.no=(r.mind.no||0)+1;r.mind.pattern=pattern(r.mind.difficulty,(now^r.mind.no)>>>0);r.mind.picked={};r.mind.wrong={};for(const u of r.users.keys()){r.mind.picked[u]=new Set();r.mind.wrong[u]=0}r.mind.puzzleEndAt=Math.min(r.mind.matchEndAt,now+16200);r.game={kind:'mind',puzzleNo:r.mind.no,startedAt:now,matchEndAt:r.mind.matchEndAt};const ids=[...r.users.keys()];for(const u of ids){const sid=[...r.sockets.entries()].find(([,x])=>x===u)?.[0];const opp=ids.find(x=>x!==u);if(sid)io.to(sid).emit('mind:state',{roomId:r.id,difficulty:r.mind.difficulty,puzzleNo:r.mind.no,pattern:r.mind.pattern,previewMs:1200,matchEndAt:r.mind.matchEndAt,puzzleEndAt:r.mind.puzzleEndAt,score:r.mind.score[u]||0,solved:r.mind.solved[u]||0,oppScore:r.mind.score[opp]||0,oppSolved:r.mind.solved[opp]||0})}clearTimeout(r.mind.timer);r.mind.timer=setTimeout(()=>{if(Date.now()>=r.mind.matchEndAt){r.mind.finished=true;const ids=[...r.users.keys()],a=ids[0],b=ids[1],sa=r.mind.score[a]||0,sb=r.mind.score[b]||0,w=sa===sb?null:sa>sb?a:b;io.to(r.id).emit('mind:match-end',{roomId:r.id,scores:r.mind.score,winnerUid:w});return}startMind(r)},16250)}
io.on('connection',s=>{
 s.on('time:ping',d=>s.emit('time:pong',{clientSentAt:Number(d?.clientSentAt)||0,serverNow:Date.now()}));
 s.on('presence:register',p=>onlineAdd(s,cleanUser(p)));
 s.on('user:search',p=>{const q=String(p?.query||'').trim().toLowerCase();if(!q)return s.emit('user:search:result',{query:q,users:[]});const out=[];for(const [uid,u] of users){if(uid.toLowerCase().includes(q)||(u.email||'').includes(q)||(u.name||'').toLowerCase().includes(q)){out.push({...u,online:(online.get(uid)?.size||0)>0});if(out.length>=20)break}}s.emit('user:search:result',{query:q,users:out})});
 s.on('room:create',p=>{const id=String(p?.roomId||'').toUpperCase(),u=cleanUser(p?.user);if(!CODE.test(id)||!u.uid)return s.emit('room:error',{message:'Invalid room or user'});const old=rooms.get(id);if(old&&old.sockets.size&&old.host!==u.uid)return s.emit('room:error',{message:'Room already exists'});const r=room(id,p?.type||'music',u.uid);r.host=u.uid;r.type=p?.type||r.type;r.users.set(u.uid,u);r.sockets.set(s.id,u.uid);s.join(id);emitState(s,r);emitUsers(r)});
 s.on('room:join',p=>{const id=String(p?.roomId||'').toUpperCase(),u=cleanUser(p?.user);if(!CODE.test(id)||!u.uid)return s.emit('room:error',{message:'Invalid room or user'});const r=rooms.get(id);if(!r)return s.emit('room:error',{message:'Room not found'});if(r.type!=='music'&&r.users.size>=2&&!r.users.has(u.uid))return s.emit('room:error',{message:'Room is full'});r.users.set(u.uid,u);r.sockets.set(s.id,u.uid);s.join(id);emitState(s,r);emitUsers(r)});
 s.on('room:leave',p=>leave(s,p?.roomId,p?.uid));
 s.on('room:request-state',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(r&&member(s,r))emitState(s,r)});
 s.on('game:request',p=>{if(p?.toUid&&p?.from?.uid)sendUid(p.toUid,'game:request',{...p,status:'pending',time:Date.now()})});
 s.on('game:request:response',p=>{if(p?.fromUid)sendUid(p.fromUid,'game:request:response',{...p,time:Date.now()})});
 s.on('room:invite',p=>{if(p?.toUid&&p?.fromUid)sendUid(p.toUid,'room:invite',{...p,time:Date.now()})});
 s.on('room:join-request',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(r&&r.host)sendUid(r.host,'room:join-request',{...p,fromUid:s.data.uid,time:Date.now()})});
 s.on('room:join-response',p=>{if(p?.toUid)sendUid(p.toUid,'room:join-response',{...p,time:Date.now()})});
 s.on('music:event',p=>{const id=String(p?.roomId||'').toUpperCase(),r=rooms.get(id);if(!r||!member(s,r)||r.host!==r.sockets.get(s.id))return;const e={...p,roomId:id,serverAt:Date.now(),hostUid:r.host,position:Math.max(0,Number(p.position)||0)};r.playback=e;s.to(id).emit('music:event',e)});
 s.on('music:request-state',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r))return;if(r.playback)s.emit('music:state',r.playback);const hs=[...r.sockets.entries()].find(([,u])=>u===r.host)?.[0];if(hs)io.to(hs).emit('music:request-state',{roomId:r.id,uid:s.data.uid})});
 s.on('game:start',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r)||r.host!==r.sockets.get(s.id)||r.users.size<2)return s.emit('room:error',{message:'Host and two players are required'});const now=Date.now();r.game={kind:String(p?.game||'game'),gameId:String(p?.gameId||('g-'+now)),startedAt:now,seed:Math.floor(Math.random()*0xffffffff)};io.to(r.id).emit('game:start',{roomId:r.id,...r.game,serverNow:now,players:members(r)})});
 s.on('game:state',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r)||!r.game)return;r.game={...r.game,state:p.state,updatedAt:Date.now(),byUid:s.data.uid};s.to(r.id).emit('game:state',{roomId:r.id,game:r.game})});
 s.on('game:event',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r)||!r.game)return;s.to(r.id).emit('game:event',{...p,roomId:r.id,serverAt:Date.now(),fromUid:s.data.uid})});
 s.on('chat:message',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(r&&member(s,r))s.to(r.id).emit('chat:message',{...p,roomId:r.id,time:Date.now(),uid:s.data.uid})});
 s.on('memory:start',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r)||r.host!==r.sockets.get(s.id)||r.users.size<2)return s.emit('room:error',{message:'Need two players before START'});r.memory={difficulty:['easy','medium','hard'].includes(p?.difficulty)?p.difficulty:'easy',round:0,scores:{},wins:{}};for(const u of r.users.keys()){r.memory.scores[u]=0;r.memory.wins[u]=0}startMemory(r)});
 s.on('memory:pick',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase()),uid=r?.sockets.get(s.id);if(!r||!uid||!r.memory||Date.now()>r.memory.deadline)return;const i=Number(p?.index),set=r.memory.picked[uid]||(r.memory.picked[uid]=new Set());if(!Number.isInteger(i)||i<0||i>=r.memory.cards.length||set.has(i))return;const ok=r.memory.cards[i]===r.memory.target;if(ok)set.add(i);s.emit('memory:feedback',{roomId:r.id,index:i,correct:ok});if(ok&&set.size===r.memory.cards.filter(x=>x===r.memory.target).length){r.memory.scores[uid]++;r.memory.wins[uid]++;io.to(r.id).emit('memory:scores',{roomId:r.id,scores:r.memory.scores,roundWins:r.memory.wins});clearTimeout(r.memory.timer);io.to(r.id).emit('memory:round-result',{roomId:r.id,winnerUid:uid,roundWins:r.memory.wins,scores:r.memory.scores});setTimeout(()=>rooms.has(r.id)&&startMemory(r),800)}});
 s.on('mind:start',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase());if(!r||!member(s,r)||r.host!==r.sockets.get(s.id)||r.users.size<2)return s.emit('room:error',{message:'Need two players before START'});const d=['easy','medium','hard'].includes(p?.difficulty)?p.difficulty:'easy';r.mind={difficulty:d,no:0,score:{},solved:{},matchEndAt:Date.now()+60000,finished:false};for(const u of r.users.keys()){r.mind.score[u]=0;r.mind.solved[u]=0}startMind(r)});
 s.on('mind:tap',p=>{const r=rooms.get(String(p?.roomId||'').toUpperCase()),uid=r?.sockets.get(s.id);if(!r||!uid||!r.mind||r.mind.finished||Date.now()>r.mind.matchEndAt||Number(p?.puzzleNo)!==r.mind.no)return;const i=Number(p?.index),set=r.mind.picked[uid]||(r.mind.picked[uid]=new Set());if(!Number.isInteger(i)||set.has(i))return;const ok=r.mind.pattern.includes(i);if(ok)set.add(i);else r.mind.wrong[uid]++;s.emit('mind:feedback',{roomId:r.id,index:i,correct:ok,score:r.mind.score[uid]||0,solved:r.mind.solved[uid]||0,wrongStreak:r.mind.wrong[uid]||0});if(ok&&set.size===r.mind.pattern.length){r.mind.score[uid]++;r.mind.solved[uid]++;io.to(r.id).emit('mind:opponent',{roomId:r.id,score:r.mind.score[uid],solved:r.mind.solved[uid]});startMind(r)}});
 s.on('disconnect',()=>{if(s.data.uid){const set=online.get(s.data.uid);if(set){set.delete(s.id);if(!set.size)online.delete(s.data.uid)}}for(const [id,r] of rooms)if(r.sockets.has(s.id))leave(s,id,s.data.uid)});
});
server.listen(PORT,()=>console.log('SonicSync Pro V9 Socket.IO server listening on '+PORT));
