export default async (request, context) => {
  const response = await context.next();
  const contentType = response.headers.get("content-type") || "";
  if (!contentType.includes("text/html")) return response;
  const html = await response.text();
  if (html.includes("viewmind-powered-popup")) return new Response(html, response);
  const injection = `<style id="viewmind-powered-popup-style">#viewmind-powered-popup{position:fixed;inset:0;z-index:2147483647;display:none;align-items:center;justify-content:center;padding:22px;background:rgba(5,8,22,.66);backdrop-filter:blur(12px)}#viewmind-powered-popup.show{display:flex}#viewmind-powered-popup .vpp-card{position:relative;width:min(420px,100%);padding:30px 24px 24px;border:1px solid rgba(129,140,248,.45);border-radius:28px;background:linear-gradient(145deg,rgba(24,28,58,.98),rgba(10,14,34,.98));box-shadow:0 28px 100px rgba(0,0,0,.58);color:#fff;text-align:center;font-family:system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}#viewmind-powered-popup .vpp-logo{width:64px;height:64px;margin:0 auto 14px;border-radius:20px;display:grid;place-items:center;background:linear-gradient(135deg,#6366f1,#ec4899);font-size:30px}#viewmind-powered-popup h3{margin:0 0 7px;font-size:22px;font-weight:900}#viewmind-powered-popup p{margin:0;color:#b8bfd5;font-size:13px}#viewmind-powered-popup .vpp-name{margin-top:9px;color:#8be9ff;font-weight:900;font-size:15px}#viewmind-powered-popup .vpp-version{margin-top:7px;color:#c7d2fe;font-size:12px;font-weight:800;letter-spacing:.5px}#viewmind-powered-popup .vpp-close{margin-top:20px;width:100%;border:0;border-radius:15px;padding:13px 18px;background:linear-gradient(135deg,#6366f1,#8b5cf6);color:#fff;font-weight:900;cursor:pointer}</style><div id="viewmind-powered-popup" aria-hidden="true"><div class="vpp-card" role="dialog" aria-modal="true"><div class="vpp-logo">✦</div><h3>ViewMind</h3><p>Website Powered by</p><div class="vpp-name">Devanand Kumar</div><div class="vpp-version">Version 2.2</div><button class="vpp-close" type="button">Close</button></div></div><script id="viewmind-powered-popup">(function(){function init(){var o=document.getElementById('viewmind-powered-popup');if(!o)return;var c=o.querySelector('.vpp-close'),k='viewmind_powered_popup_seen_v2_2';function h(){o.classList.remove('show');o.setAttribute('aria-hidden','true')}c.addEventListener('click',h);o.addEventListener('click',function(e){if(e.target===o)h()});document.addEventListener('keydown',function(e){if(e.key==='Escape')h()});try{if(!sessionStorage.getItem(k)){sessionStorage.setItem(k,'1');o.classList.add('show');o.setAttribute('aria-hidden','false')}}catch(_){o.classList.add('show')}}if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init()})();</script>`;
  const marker="</body>"; const output=html.includes(marker)?html.replace(marker,injection+marker):html+injection; const headers=new Headers(response.headers);headers.delete("content-length");return new Response(output,{status:response.status,statusText:response.statusText,headers});
};
